export const ADD_WORKPLACE = 'ADD_WORKPLACE';
export const CHANGE_SELECTED_WORKPLACE = 'CHANGE_SELECTED_WORKPLACE';
export const ADD_WORKPLACE_REQUEST = 'ADD_WORKPLACE_REQUEST';
export const ADD_WORKPLACES = 'ADD_WORKPLACES';
export const ADD_SELECTED_WORKPLACE = 'ADD_SELECTED_WORKPLACE';
export const DELETE_WORKPLACE = 'DELETE_WORKPLACE';
